# Generated by Django 3.0.2 on 2020-02-24 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=100)),
                ('movie_released', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='movieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_generay', models.CharField(max_length=25)),
                ('movie_type', models.CharField(max_length=20)),
                ('members', models.ManyToManyField(to='gum.movies')),
            ],
        ),
    ]
