# Generated by Django 3.0.2 on 2020-02-24 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movietype',
            old_name='members',
            new_name='movies',
        ),
    ]
