# Generated by Django 3.0.2 on 2020-02-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gum', '0002_auto_20200224_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_actor',
            field=models.CharField(default=99, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movies',
            name='movies_actress',
            field=models.CharField(default=99, max_length=100),
            preserve_default=False,
        ),
    ]
